version: '3.8'

services:
  db:
    image: postgres:16
    container_name: newscenter-db
    restart: always
    environment:
      POSTGRES_USER: newscenter
      POSTGRES_PASSWORD: nc_secret
      POSTGRES_DB: newscenter
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d 

  backend:
    build: ./backend
    container_name: newscenter-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=newscenter
      - DB_PASSWORD=nc_secret
      - DB_NAME=newscenter
      - JWT_SECRET=super_secret_jwt_key_123
      - LDAP_URL=ldap://ldap.technikum-wien.at
      - LDAP_BASE_DN=ou=people,dc=technikum-wien,dc=at
    volumes:
      - ./backend/src:/app/src  # Live-Reload: Änderungen werden sofort übernommen
    command: npm run dev         # nodemon statt node
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: newscenter-frontend
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  db-data: